enum ErrorCode {
    NOT_EXIST = 'ERR_DATA_NOT_EXIST',
    EXISTED = 'ERR_DATA_EXISTED',
    INVALID = 'ERR_DATA_INVALID',
    AUTH_FAILURE = 'ERR_AUTH_FAILURE',
    INTERNAL = 'ERR_INTERNAL_SERVER'
}

export default ErrorCode;